### ISSUE TITLE
difference key when reload page.

### ISSUE THREAD

**Issue by keawchot** [tasti/react-linkify#3]
React attempted to reuse markup in a container but the checksum was invalid. This generally means that you are using server rendering and the markup generated on the server was not what the client was expecting. React injected new markup to compensate which works but you have lost many of the benefits of server rendering. Instead, figure out why the markup being generated is different on the client or server.

**Comment by tasti** [comment]
I'm sorry, can you elaborate? Is that an error that you saw? How can I reproduce it?

**Comment by indeyets** [comment]
@tasti the issue is, that component is not isomorphic-rendering friendly. It uses static counter for `$LINKIFY_KEY_XXX` which keeps increasing while server handles various requests. So, when user opens page with linkify, react gives a warning about markup differences:

![eb9109d0-8217-40b1-b2a4-ba6ce78857e5 2015-10-15 23-32-54](https://cloud.githubusercontent.com/assets/13445/10526708/14660a90-7395-11e5-81e0-b5e918c05d95.jpg)

**Comment by indeyets** [comment]
I'm not even convinced, that keys are needed in case of linkify. it's not like it is a list or reorderable items

**Comment by indeyets** [comment]
ok. as far as I understand, keys are used to distinguish sibling elements. it means that you do not need truly unique keys. you just need ordered keys for each parsed area. I'll make a pull-request
