### ISSUE TITLE
Troubles with react 0.15

### ISSUE THREAD

**Issue by vojtatranta** [tasti/react-linkify#32]
Hello,
thank for this great package.

But I have encountered an issue recently. Since version `0.1.2`, `0.1.1` works OK.

I get an error when linkify is renderer which completely breaks down React rendering and it is just stuck. 

The error:
```
React.createElement: type is invalid -- expected a string (for built-in components) or a class/function (for composite components) but got: object. Check the render method of `NoteBoxCommentItem`.
```
No changes in my markup was made, only thing that changed is `react-linkify` version.

**Comment by katpas** [comment]
Is there a fix or explanation for this one? I've had to use a different module as getting the same error.

**Comment by triple1c86** [comment]
yea same problem..

**Comment by cebrakadabra** [comment]
Yo!

I just did a PR for this. 
i recoded the component to make it working in higher react versions.
I just imported that file via, to test it:

```import Linkify from 'Linkify.jsx';```

https://github.com/tasti/react-linkify/pull/35/files

**Comment by maksis** [comment]
@cebrakadabra what was the exact issue with the code that you solved?

The current release should work fine when using ES6 imports:

`import Linkify from 'react-linkify'`

Or with CommonJS:

`var Linkify = require('react-linkify').default;`

That behavior is caused by Babel 6 upgrade in commit https://github.com/tasti/react-linkify/commit/6ead6fec47d0b54968445f66a431d2fd1766b1fa which [changes the way how `export default` works](http://stackoverflow.com/questions/33505992/babel-6-changes-how-it-exports-default)

@tasti the usage example in README is currently broken

**Comment by cebrakadabra** [comment]
@maksis i restructured the whole Linkify component itself to make an element out of it. Because you aren't accessing any functions from outside and you are not reliable on the state of this one, so I thought it's probably easier doing it that way. 

i got the same error as reported from other people here: 
```React.createElement: type is invalid -- expected a string (for built-in components)```

So, I used that as a motivation to make an Element out of it while debugging the error, which was probably just a wrong usage of `import { Linkify } from ...` instead of `import Linkify from ...` on my end. Basically that's what the error describes.

Furthermore: https://facebook.github.io/react/blog/2015/12/18/react-components-elements-and-instances.html


```
An element is a plain object describing a component instance or DOM node and its desired properties. It contains only information about the component type (for example, a Button), its properties (for example, its color), and any child elements inside it.

An element is not an actual instance. Rather, it is a way to tell React what you want to see on the screen. You can’t call any methods on the element. It’s just an immutable description object with two fields: type: (string | ReactClass) and props: Object1.
```

**Comment by Wayne-Ehr-Surprenant** [comment]
I had the same issue. I just used the
 `import Linkify from 'react-linkify';`

instead of 
`var Linkify = require('react-linkify');`
and now it works!

**Comment by tasti** [comment]
This looks like an importing issue as described and solved by @maksis. I'll update the README.
