### ISSUE TITLE
open link in a new tab?

### ISSUE THREAD

**Issue by Pegahkeshavarz** [tasti/react-linkify#48]
Is there anyway to open the link in a new tab? right now it opens it in the same tab

**Comment by joojis** [comment]
According to the demo(http://tasti.github.io/react-linkify/), 

<Linkify properties={{target: '_blank'}> ... </Linkify>

**Comment by tasti** [comment]
One possibility is instead of using `properties`, you can just place the props you want each of your links to have directly on `Linkify`. For example:

```
<Linkify target="_blank">...</Linkify>
```

My worry here is that there may be some overlap that isn't ideal, where there's a prop on `Linkify` that is also on `a` but with different values. I think there are little to none of these, and seems to be more intuitive.

**Comment by jb-reefer** [comment]
@tasti I'd be happy to implement the target idea and make a PR if you're interested

**Comment by tasti** [comment]
Would love to include this, give it a shot :)

**Comment by dharness** [comment]
@jb-reefer presuming this didn't happen?

**Comment by jb-reefer** [comment]
@dharness never got the shot - I can work on it this weekend, but if you want to do it feel free!

**Comment by jb-reefer** [comment]
@dharness submitted a PR!

**Comment by dharness** [comment]
Hey didn't expect that! Much appreciated!

**Comment by tasti** [comment]
See https://github.com/tasti/react-linkify/pull/51#issuecomment-355787057.

**Comment by Jayanth998** [comment]
Add target: "_blank" property as part of options prop
