### ISSUE TITLE
Is this project maintained?

### ISSUE THREAD

**Issue by fredvollmer** [tasti/react-linkify#55]
I've noticed there's a backlog of PR's...is a new/additional maintainer needed? This is a wonderful library which we get a lot of value out of, and we'd be happy to lend a hand.

**Comment by tasti** [comment]
Hey, I really appreciate the enthusiasm! Honestly, I haven't put a lot of priority maintaining due to the existing state solving 90% of use-cases. I've noticed a lot of interest recently in some additional core features (like #54) that would be great to add. I have some time on my hands so I'm happy to get through the backlog in the coming weeks. Look out for updates very soon :)

**Comment by fredvollmer** [comment]
Sounds great @tasti. Thanks for all the work.
